from tkinter import *
window = Tk()
window.geometry("1600x800+50+100")
bg = PhotoImage(file = "bg.png")
albon = PhotoImage(file= "imgs/alabona.png")
bottas = PhotoImage(file= "imgs/Bottas.png")
Carlos = PhotoImage(file= "imgs/Carlos.png")
Charles = PhotoImage(file= "imgs/Charles.png")
Checo = PhotoImage(file= "imgs/Checo.png")
estenba = PhotoImage(file= "imgs/estenba.png")
Fernando = PhotoImage(file= "imgs/Fernando.png")
gasly = PhotoImage(file= "imgs/gasman.png")
george = PhotoImage(file= "imgs/George.png")
latifi = PhotoImage(file= "imgs/Goatifi.png")
kmag = PhotoImage(file= "imgs/K-mag.png")
jewis = PhotoImage(file= "imgs/Lewis.png")
Max = PhotoImage(file= "imgs/MaxVerstappen.png")
mick = PhotoImage(file= "imgs/mcik.png")
lando = PhotoImage(file= "imgs/Nando.png")
seb = PhotoImage(file= "imgs/seb.png")
stroll = PhotoImage(file= "imgs/stroll.png")
yuki = PhotoImage(file= "imgs/yuki.png")
Zhou = PhotoImage(file= "imgs/Zhou.png")
daniel = PhotoImage(file= "imgs/Daniel.png")
bg2 = PhotoImage(file= "bg2.png")
def driverroom():
    print("Cock")
    button2.place_forget()
    button1.place_forget()
    label1.place_forget()
    label2 = Label(window, image= bg2)
    label2.place(x=0,y=0)


playbutton = PhotoImage(file= "imgs/playbutton.png")
settings = PhotoImage(file= "imgs/Settings.png")
label1 = Label(window, image = bg)
label1.place(x = 0, y = 0)
button1 = Button(window, image= playbutton,command=driverroom)
button1.place(x=100,y=250)
button2 = Button(window, image= settings)
button2.place(x=100,y=550)

window.mainloop()